ALTER TABLE users
    ADD COLUMN reminder_freq VARCHAR(20) NOT NULL DEFAULT 'never',
    ADD COLUMN reminder_time TIME NOT NULL DEFAULT '10:00:00',
    ADD COLUMN utc_reminder_hour SMALLINT NOT NULL DEFAULT 10,
    ADD COLUMN timezone TEXT NOT NULL DEFAULT 'UTC',
    ADD COLUMN locale VARCHAR(10) NOT NULL DEFAULT 'fr';
